### ISSUE TITLE
Errors when starting from client

### ISSUE THREAD

**Issue by miri-am** [alanning/meteor-trace#1]
```
SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function alanning_trace.js:426:13
TypeError: Package['alanning:trace'] is undefined
```

**Comment by alanning** [comment]
Can you expand a bit more on this and/or publish a reproduction to github, please?

The following steps work for me.  Do they work for you?

```
kaia2:~$ cd tmp
kaia2:~/tmp$ meteor create foo2
foo2: created.

To run your new app:
  cd foo2
  meteor
kaia2:~/tmp$ cd foo2
kaia2:~/tmp/foo2$ meteor add alanning:trace

Changes to your project's package version selections:

alanning:trace  added, version 0.0.1


alanning:trace: Log client-side Meteor events
kaia2:~/tmp/foo2$ meteor
[[[[[ ~/tmp/foo2 ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
```

**Comment by miri-am** [comment]
I am not familiar with strict-mode, but the top-level `"use strict"`in the templates.js file is causing these errors. When I comment it out, it works fine.

**Comment by alanning** [comment]
Thanks for narrowing that down.  Can you publish an app that reproduces the issue to github, please?

**Comment by alanning** [comment]
OK, was able to reproduce in Firefox console (works in Chrome).  I think its the `makeWrapper` function.  Should have a fix shortly.

**Comment by alanning** [comment]
Please have a try with the new version.  You can use it by cloning the repo into your app's packages directory, like this:

```
$ cd myApp
$ mkdir packages
$ cd packages
$ git clone https://github.com/alanning/meteor-trace.git alanning_trace
```

That should make meteor use the version in the cloned repo (the latest).  Alternately you can change the template.js file as I did in the [commit](https://github.com/alanning/meteor-trace/commit/b82cffe009dcfef19a698656b8a676c85de6a745).

**Comment by miri-am** [comment]
Yes that version works. Thanks! Sorry, forgot to mention my browser: Firefox 37.0.1
