### ISSUE TITLE
Template helper with parameter returns "Invalid Date" in Firefox

### ISSUE THREAD

**Issue by miri-am** [alanning/meteor-trace#2]
Reproduction: https://github.com/miri-am/test-trace

This only occurs in Firefox but works fine in Chome. 

The helper returns "Invalid Date" in Firefox when invoked with a parameter: 

```
{{createdAtFormatted "2015-04-28T06:36:20.939Z"}}
```

```
createdAtFormatted: function (time) {
      return moment(time).format('MM/DD/YYYY, HH:MM'); //returns "Invalid Date" in Firefox when trace package is added
}
```

When used without a parameter like it works:

```
{{createdAtFormatted}}
```

```
createdAtFormatted: function () {
      return moment(this.time).format('MM/DD/YYYY, HH:MM'); //works
}
```

Sorry to bother, but thought maybe someone else comes around this and wonders why some helper is not returning the correct value anymore.

And thanks for the package - it is really helpful for me!

**Comment by alanning** [comment]
Thanks for reporting and including a repro. Very helpful.

I'll work on this today so hopefully should have a fix tonight.

Also, thanks for trying out the package.  Seems you are the first one so hitting all the rough edges.  :-)

**Comment by alanning** [comment]
Trace version 0.0.2 published with fixes for this and the first issue.
